name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server in background
        run: |
          uvicorn apiserver:app --host 127.0.0.1 --port 8000 &
          sleep 5  # Give it a moment to start

      - name: Run tests
        run: pytest test_automation.py
